import {createSlice} from "@reduxjs/toolkit"
const clientslice=createSlice({
    name:"client",
    initialState:{
        Logindata:{
            name:"",
            email:"",
            password:""
        },
        backendemail:"",
        type:"Sign up",
        navclass:"",
        Account:"student",
        backendemail2:"",
        sidemenu:"",
        image:"",
        Coursedata:{
            name:"",
            description:"",
            module:"",

        },
        Notesdata:{
            authorname:"",
            subject:"",
            status:"",
            price:""
        },
        courseloading:false,
        studentcourse:[],
        Totalteachercourses:[],
        displayloading:false,
        quizstatus:false,
        totalquestions:"",
        quizlen:false,
        quizquestions:[],
        quizsubject:"",
        totalteacherquiz:[],
        quizmaindata:[],
        quizid:"",
        quizdetails:[],
        feedbacks:[],
        notesfile:"",
        notesloading:false,
        Notes:[]
        
},
reducers:{
    setLogindata(state,action){
        const {name,value}=action.payload;
        state.Logindata[name]=value;
    },
    setNotes(state,action){
        state.Notes=action.payload;
    },
    setnotesloading(state,action){
        state.notesloading=action.payload;
    },
    setNotesdata(state,action){
        const {name,value}=action.payload;
        state.Notesdata[name]=value;
    },
    setnotesfile(state,action){
        state.notesfile=action.payload;
    },
    setfeedbacks(state,action){
        state.feedbacks=action.payload;
    },
    setquizdetails(state,action){
        state.quizdetails=action.payload;
    },
    setquizid(state,action){
        state.quizid=action.payload;
    },
    setquizmaindata(state,action){
        state.quizmaindata=action.payload;
    },
    settotalteacherquiz(state,action){
        state.totalteacherquiz=action.payload;
    },
    setquizquestions(state,action){
        state.quizquestions=action.payload;
    },
    setquizsubject(state,action){
        state.quizsubject=action.payload
    },
    setquizlen(state,action){
        state.quizlen=action.payload;
    },
    settotalquestions(state,action){
        state.totalquestions=action.payload;
    },
    setquizstatus(state,action){
        state.quizstatus=action.payload;
    },
    setdisplayloading(state,action){
        state.displayloading=action.payload;

    },
    setTotalteachercourses(state,action){
        state.Totalteachercourses=action.payload;
    },
    updatequizquestion(state,action){
        const {index,name,value}=action.payload;
        state.quizquestions[index][name]=value
    },
    setstudentcourse(state,action){
        state.studentcourse=action.payload;
    },
    setcourseloading(state,action){
        state.courseloading=action.payload;
    },
    setCoursedata(state,action){
        const {name,value}=action.payload;
        state.Coursedata[name]=value;
    },
    setimage(state,action){
        state.image=action.payload;
    },
    setsidemenu(state,action){
        state.sidemenu=action.payload;
    },
    setbackendemail2(state,action){
        state.backendemail2=action.payload;
    },
   setnavclass(state,action){
        state.navclass=action.payload;
    },
    setAccount(state,action){
        state.Account=action.payload;
    },
    setbackendemail(state,action){
        state.backendemail=action.payload;
    },
    settype(state,action){
        state.type=action.payload;
    }
}
})
export const control=clientslice.actions;
export default clientslice.reducer;